services:
  database:
    image: mongo
    container_name: find9_database
    ports:
      - 27017:27017
    volumes:
      - ./database/data/db:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - lan
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command:
      - /bin/sh
      - -c
      - |
        mongod --bind_ip_all
    profiles:
      - donotstart

  web:
    build:
      context: ./web
    image: find9_web
    container_name: web
    ports:
      - 8000:80
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
      - ./modules:/usr/src/app/modules
    networks:
      - lan
    #profiles:
    #  - donotstart

  forum:
    build:
      context: ./forum
    image: find9_forum
    container_name: forum
    ports:
      - 8001:80
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
      - ./modules:/usr/src/app/modules
    networks:
      - lan
    profiles:
      - donotstart

  api:
    build:
      context: ./api
    image: find9_api
    container_name: api
    ports:
      - 8002:80
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
      - ./modules:/usr/src/app/modules
    networks:
      - lan
    profiles:
      - donotstart

networks:
  lan:
    driver: bridge
